# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/blogs/rss_feed.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/blogs/rss_feed.proto", :syntax => :proto3) do
    add_message "portfolio.blogs.RSSFeed" do
      optional :id, :string, 1
      optional :url, :string, 2
    end
    add_message "portfolio.blogs.CreateRSSFeedRequest" do
      optional :url, :string, 2
    end
  end
end

module RSSFeedsPb
  RSSFeed = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("portfolio.blogs.RSSFeed").msgclass
  CreateRSSFeedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("portfolio.blogs.CreateRSSFeedRequest").msgclass
end
