# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/api.proto for package 'ApiPb'

require 'grpc'
require 'proto/api_pb'

module ApiPb
  module PortfolioBackendApi
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'portfolio.PortfolioBackendApi'

      rpc :CreateRSSFeed, ::RSSFeedsPb::CreateRSSFeedRequest, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
