# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/api.proto for package 'ApiPb'

require 'grpc'
require 'proto/api_pb'

module ApiPb
  module PortfolioBackendApi
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'portfolio.PortfolioBackendApi'

      # For RSS Feed ========================
      rpc :CreateRSSFeed, ::RSSFeedsPb::CreateRSSFeedRequest, ::Google::Protobuf::Empty
      rpc :BatchGetRSSFeeds, ::Google::Protobuf::Empty, ::RSSFeedsPb::BatchGetRSSFeedsResponse
      rpc :GetRSSFeed, ::RSSFeedsPb::GetRSSFeedRequest, ::RSSFeedsPb::GetRSSFeedResponse
      rpc :DeleteRSSFeed, ::RSSFeedsPb::DeleteRSSFeedRequest, ::Google::Protobuf::Empty
      # For Blog ============================
      rpc :CreateBlog, ::BlogsPb::CreateBlogRequest, ::Google::Protobuf::Empty
      rpc :BatchGetBlogs, ::Google::Protobuf::Empty, ::BlogsPb::BatchGetBlogsResponse
      rpc :GetBlog, ::BlogsPb::GetBlogRequest, ::BlogsPb::GetBlogResponse
      rpc :DeleteBlog, ::BlogsPb::DeleteBlogRequest, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
